"""
Real-time UI localization dictionary for CareLens AI companion.
Supports 13 global and Indic regional languages.
"""

from typing import Dict, Any


TRANSLATIONS: Dict[str, Dict[str, str]] = {
    'English': {
        'seniorBadge': 'Senior Companion Mode Active',
        'textSizePrefix': 'Text:',
        'textSizeNormal': 'Normal',
        'textSizeLarge': 'Large',
        'textSizeHuge': 'Huge',
        'whatsappBtn': 'WhatsApp',
        'apiKeyBtn': 'API Key',
        'heroTitle': 'Point at Anything — CareLens Explains It!',
        'heroDesc': 'Point your camera at any item, medicine bottle, paper bill, appliance dial, food, or letter. Tap one button and CareLens will speak what it is and what to do.',
        'aiStatusTitleNoKey': 'Live AI Status: API Key Needed for Real Image Analysis',
        'aiStatusSubtitleNoKey': 'To analyze real photos with Google Gemini AI, please enter your free API key.',
        'aiStatusTitleKey': '✅ Live AI Connected: Google Gemini Vision is Active',
        'aiStatusSubtitleKey': 'Your photos will be analyzed in real-time by Gemini AI.',
        'setApiKeyBtn': '🔑 Set API Key',
        'cameraBtnTitle': 'Tap Here to Open Camera',
        'cameraBtnSub': 'Opens live camera viewfinder to scan anything',
        'uploadBtn': '📁 Or Upload Photo / Document from Device',
        'sampleTitle': '💡 Testing without a physical object? Try quick sample images',
        'sampleClick': 'Click to expand',
        'sampleMed': '💊 Medicine Bottle',
        'sampleBill': '⚡ Electric Bill',
        'sampleScam': '🚨 Suspicious Letter',
        'loadingTitle': 'Analyzing Your Photo...',
        'loadingDesc': 'Please give CareLens just a moment. We are consulting Gemini AI.',
        'scanAnotherBtn': '⬅️ Scan Another',
        'photoCaptured': 'Photo captured',
        'plainSummaryBadge': 'Plain Language Summary',
        'voiceCompanion': 'Voice Audio Companion',
        'voicePace': 'Gentle pace (0.88x speed) for easy listening',
        'readAloud': 'Read Aloud to Me',
        'pauseReading': 'Pause Reading',
        'askTitle': 'Have a question about this? Ask CareLens:',
        'questionPlaceholder': 'Type your question here...',
        'askBtn': 'Ask CareLens This Question',
        'voiceStatusDefault': 'e.g. "When should I take this?" or "Is this a scam?"',
        'voiceStatusListening': '🎙️ Listening... speak now',
        'voiceStatusError': 'Could not hear clearly. Tap mic to try again.',
        'answerTitle': 'CareLens Answer:',
        'readAnswerAloud': '🔊 Read Answer Aloud',
        'caregiverTitle': 'Want a second opinion?',
        'caregiverDesc': 'Send this summary to your family or caregiver on WhatsApp.',
        'sendFamily': 'Send to Family (WhatsApp)',
        'sendOther': 'Send to Other Number',
        'savedCaregiverPrefix': 'Saved caregiver: +',
        'savedCaregiverSuffix': ' — tap to share instantly.',
        'noCaregiverHint': 'Set a caregiver number (💬 in toolbar) for one-tap sharing.',
        'promptEnterWa': 'Enter WhatsApp number with country code (e.g. 14155552671):',
        'webcamHeader': '📹 Point camera at anything',
        'webcamReticle': 'Hold item inside this frame',
        'webcamSnap': '📸 Tap to Take Photo Now',
        'webcamCancel': 'Cancel and go back',
        'apiKeyModalTitle': '🔑 Connect Gemini AI',
        'apiKeyModalDesc': 'Enter your Google Gemini API key to activate real AI vision on your photos.',
        'apiKeyModalLink': '👉 Get a free key in 30 seconds at:',
        'apiKeyModalSave': '✔ Save & Connect',
        'apiKeyModalCancel': 'Cancel',
        'apiKeyModalNote': '🔒 Your key is stored only in your browser (localStorage). Never shared.',
        'waModalTitle': 'Caregiver WhatsApp',
        'waModalDesc': 'Save your family member or caregiver\'s WhatsApp number for instant 1-tap second opinion sharing.',
        'waModalLabel': 'Phone Number (with country code)',
        'waModalSave': '✔ Save Number',
        'waModalCancel': 'Cancel',
        'waModalNote': '🔒 Stored locally on this device.',
        'closePhoto': 'Close Photo'
    },
    'Hindi': {
        'seniorBadge': 'वरिष्ठ साथी मोड सक्रिय',
        'textSizePrefix': 'अक्षर:',
        'textSizeNormal': 'सामान्य',
        'textSizeLarge': 'बड़ा',
        'textSizeHuge': 'विशाल',
        'whatsappBtn': 'व्हाट्सएप',
        'apiKeyBtn': 'एपीआई कुंजी',
        'heroTitle': 'किसी भी वस्तु पर कैमरा लगाएं — केयरलेंस समझाएगा!',
        'heroDesc': 'दवाई की शीशी, बिजली का बिल, पत्र या किसी वस्तु पर कैमरा लगाएं। एक बटन दबाएं और केयरलेंस बोलकर समझाएगा।',
        'aiStatusTitleNoKey': 'लाइव एआई स्थिति: वास्तविक विश्लेषण के लिए एपीआई कुंजी आवश्यक',
        'aiStatusSubtitleNoKey': 'गूगल जेमिनी एआई द्वारा विश्लेषण के लिए कृपया अपनी मुफ्त एपीआई कुंजी दर्ज करें।',
        'aiStatusTitleKey': '✅ लाइव एआई कनेक्टेड: गूगल जेमिनी विज़न सक्रिय है',
        'aiStatusSubtitleKey': 'आपकी तस्वीरें जेमिनी एआई द्वारा रीयल-टाइम में समझी जाएंगी।',
        'setApiKeyBtn': '🔑 एपीआई कुंजी सेट करें',
        'cameraBtnTitle': 'कैमरा खोलने के लिए यहाँ टैप करें',
        'cameraBtnSub': 'किसी भी वस्तु को स्कैन करने के लिए लाइव कैमरा खोलता है',
        'uploadBtn': '📁 या डिवाइस से फोटो / दस्तावेज़ अपलोड करें',
        'sampleTitle': '💡 क्या आपके पास कोई वस्तु नहीं है? नमूना चित्र आज़माएं',
        'sampleClick': 'खोलने के लिए टैप करें',
        'sampleMed': '💊 दवाई की शीशी',
        'sampleBill': '⚡ बिजली का बिल',
        'sampleScam': '🚨 संदिग्ध पत्र / धोखाधड़ी',
        'loadingTitle': 'आपकी फोटो का विश्लेषण हो रहा है...',
        'loadingDesc': 'कृपया कुछ पल प्रतीक्षा करें। केयरलेंस एआई से परामर्श ले रहा है।',
        'scanAnotherBtn': '⬅️ दूसरा स्कैन करें',
        'photoCaptured': 'फोटो खींची गई',
        'plainSummaryBadge': 'सरल भाषा में सारांश',
        'voiceCompanion': 'आवाज साथी',
        'voicePace': 'सहज गति (0.88x रफ्तार) सुनने में आसान',
        'readAloud': 'मुझे बोलकर सुनाएं',
        'pauseReading': 'पढ़ना रोकें',
        'askTitle': 'क्या आपका कोई सवाल है? केयरलेंस से पूछें:',
        'questionPlaceholder': 'अपना सवाल यहाँ लिखें...',
        'askBtn': 'केयरलेंस से यह सवाल पूछें',
        'voiceStatusDefault': 'उदा. "मुझे यह कब लेना चाहिए?" या "क्या यह धोखाधड़ी है?"',
        'voiceStatusListening': '🎙️ सुन रहा हूँ... अब बोलें',
        'voiceStatusError': 'स्पष्ट सुनाई नहीं दिया। माइक पर फिर से टैप करें।',
        'answerTitle': 'केयरलेंस का जवाब:',
        'readAnswerAloud': '🔊 जवाब बोलकर सुनाएं',
        'caregiverTitle': 'परिवार की राय चाहिए?',
        'caregiverDesc': 'यह सारांश अपने परिवार या देखभालकर्ता को व्हाट्सएप पर भेजें।',
        'sendFamily': 'परिवार को भेजें (WhatsApp)',
        'sendOther': 'अन्य नंबर पर भेजें',
        'savedCaregiverPrefix': 'सहेजा गया नंबर: +',
        'savedCaregiverSuffix': ' — तुरंत भेजने के लिए टैप करें।',
        'noCaregiverHint': '1-टैप शेयरिंग के लिए देखभालकर्ता नंबर (टूलबार में 💬) सेट करें।',
        'promptEnterWa': 'देश कोड सहित व्हाट्सएप नंबर दर्ज करें (उदा. 919876543210):',
        'webcamHeader': '📹 किसी भी वस्तु पर कैमरा लगाएं',
        'webcamReticle': 'वस्तु को इस चौखट के अंदर रखें',
        'webcamSnap': '📸 फोटो लेने के लिए यहाँ टैप करें',
        'webcamCancel': 'रद्द करें और वापस जाएं',
        'apiKeyModalTitle': '🔑 जेमिनी एआई कनेक्ट करें',
        'apiKeyModalDesc': 'अपनी फोटो पर असली एआई विज़न सक्रिय करने के लिए जेमिनी एपीआई कुंजी दर्ज करें।',
        'apiKeyModalLink': '👉 30 सेकंड में मुफ्त कुंजी प्राप्त करें:',
        'apiKeyModalSave': '✔ सहेजें और कनेक्ट करें',
        'apiKeyModalCancel': 'रद्द करें',
        'apiKeyModalNote': '🔒 आपकी कुंजी केवल आपके ब्राउज़र में सुरक्षित रहती है।',
        'waModalTitle': 'परिवार / देखभालकर्ता व्हाट्सएप',
        'waModalDesc': '1-टैप शेयरिंग के लिए अपने परिवार का व्हाट्सएप नंबर सहेजें।',
        'waModalLabel': 'फोन नंबर (देश कोड के साथ)',
        'waModalSave': '✔ नंबर सहेजें',
        'waModalCancel': 'रद्द करें',
        'waModalNote': '🔒 इस डिवाइस पर सुरक्षित रूप से सहेजा गया।',
        'closePhoto': 'फोटो बंद करें'
    }
}


def get_translations_for_language(language: str = 'English') -> Dict[str, str]:
    """
    Get localized string dictionary for specified language, falling back to English.
    """
    return TRANSLATIONS.get(language, TRANSLATIONS['English'])
