# Generated by Django 6.1.1 on 2026-09-20 10:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Senior User', help_text='Preferred name or greeting', max_length=100)),
                ('preferred_language', models.CharField(default='English', help_text='Primary UI and speech language', max_length=50)),
                ('font_scale', models.CharField(choices=[('Normal', 'Normal'), ('Large', 'Large'), ('Huge', 'Huge')], default='Normal', help_text='Magnified typography scale', max_length=20)),
                ('theme_preference', models.CharField(choices=[('light', 'Warm Linen (Light)'), ('dark', 'Midnight Slate (Comfort Dark)')], default='light', help_text='Visual comfort theme', max_length=20)),
                ('speech_rate', models.FloatField(default=0.88, help_text='Calibrated speech rate for senior hearing (0.7 - 1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Senior Profile',
                'verbose_name_plural': 'Senior Profiles',
            },
        ),
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('MEDICATION', 'Medication Prescription'), ('BILLING', 'Utility / Financial Bill'), ('SECURITY_CHECK', 'Security / Scam Verification'), ('APPLIANCE', 'Appliance Dial / Control'), ('FOOD', 'Food Expiration / Nutrition'), ('NOTICE', 'General Paper Notice'), ('GENERAL', 'General Object')], default='GENERAL', max_length=40)),
                ('summary_text', models.TextField(help_text='2-sentence senior-tailored plain language explanation')),
                ('safety_verdict', models.CharField(choices=[('SAFE', 'Verified Safe'), ('CAUTION', 'Proceed with Caution'), ('SCAM', 'Danger - Scam Detected')], default='SAFE', max_length=20)),
                ('safety_explanation', models.TextField(blank=True, default='')),
                ('primary_action_label', models.CharField(blank=True, default='', max_length=100)),
                ('primary_action_value', models.CharField(blank=True, default='', max_length=100)),
                ('secondary_action_label', models.CharField(blank=True, default='', max_length=100)),
                ('secondary_action_value', models.CharField(blank=True, default='', max_length=100)),
                ('caregiver_message', models.TextField(blank=True, default='')),
                ('language_used', models.CharField(default='English', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('senior_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companion.seniorprofile')),
            ],
            options={
                'verbose_name': 'Scan Record',
                'verbose_name_plural': 'Scan Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaregiverContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Family Caregiver', max_length=100)),
                ('relationship', models.CharField(default='Daughter/Son', help_text='e.g. Son, Daughter, Nurse', max_length=50)),
                ('phone_number', models.CharField(help_text='E.164 formatted number with country code', max_length=30)),
                ('is_primary', models.BooleanField(default=True, help_text='Primary contact for 1-tap sharing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('senior_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caregivers', to='companion.seniorprofile')),
            ],
            options={
                'verbose_name': 'Caregiver Contact',
                'verbose_name_plural': 'Caregiver Contacts',
            },
        ),
    ]
