# Generated by Django 6.1.1 on 2026-09-20 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorprofile',
            name='has_completed_tour',
            field=models.BooleanField(default=False, help_text='Whether senior user has finished the onboarding walkthrough'),
        ),
        migrations.AddField(
            model_name='seniorprofile',
            name='role',
            field=models.CharField(choices=[('senior', 'Senior User'), ('caregiver', 'Family Caregiver')], default='senior', help_text='User role (Senior or Family Caregiver)', max_length=20),
        ),
        migrations.AddField(
            model_name='seniorprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senior_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
