# Generated by Django 6.1.1 on 2026-09-27 08:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0002_seniorprofile_has_completed_tour_seniorprofile_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person raising the ticket', max_length=100)),
                ('email', models.EmailField(help_text='Reply-to email for support response', max_length=254)),
                ('category', models.CharField(choices=[('camera', '📸 Camera / Scanning Issue'), ('voice', '🔊 Voice or Audio Problem'), ('language', '🌐 Language / Translation Issue'), ('account', '👤 Account or Login Problem'), ('whatsapp', '💬 WhatsApp Sharing Issue'), ('ai_result', '🤖 AI Result Not Correct'), ('accessibility', '♿ Accessibility or Display Issue'), ('other', '❓ Other / General Question')], default='other', max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(help_text='Detailed description of the issue')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('ticket_id', models.CharField(blank=True, help_text='Auto-generated short ticket reference', max_length=16, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
